### ISSUE TITLE
Creation of Data Models 

### ISSUE THREAD

**Issue by dorianbucknor** [dbucknor/ap-grizzly-entertainment#3]
Create data classes inside `com.grizzly.application.models` package from the uml diagram. All classes should be serializable, and should have Primary, Secondary and Copy constructors and implement `toString` method. 

`Equipment` class and its child classes: `Sound`, `Light`. `Power` and `Stage` - @Blckreaper 

`Customer`, `Employee`, `Address` - @MugiJM 

`Invoice`, `ReantalRequest`, `Maintenence Log` - @Roku458 

Should not take more than a week to complete.

Use `models` branch to add classes. After completion, push changes to the branch. 
> **Do not merge to `main` or `dev` branch!**

**Comment by dbucknor** [comment]
Any updates?
Deadline Passed.

**Comment by Blckreaper** [comment]
The only thing left was to finish up some methods in The child and parent class for my assignment...they took the back burner because mid semester tests and assignments

**Comment by dbucknor** [comment]
okkl

**Comment by Roku458** [comment]
for the maintenance log is it the log properties file you want or what.

**Comment by Roku458** [comment]
these also weren't my top prio cause i have 3 tests this week. sorry

**Comment by dbucknor** [comment]
For the maintenance log, it would have been a custom class to store maintenance info on the equipment including the condition of the equipment. 

> for the maintenance log is it the log properties file you want or what.

**Comment by Roku458** [comment]
oh ok

**Comment by MugiJM** [comment]
Will be adding my part soon. I had some tests and projects due so I wasn't focusing on this. My apologies.
