### ISSUE TITLE
Creation Of UI Pages (Views) - Set 1

### ISSUE THREAD

**Issue by dbucknor** [dbucknor/ap-grizzly-entertainment#7]
Create Screens for display as shown in design files. Data models are also to be created for Screens where necessary. Use various layout styles etc to acheivement the closest possible look. 

Use the `ThemeManager` to get the application's specific colors. Commit changes and push to `views` branch.
To use `ThemeManager` - `ThemeManager themeManager = ThememManager.getInstance();`

> All Screens Must extend `Screen` class as this class has the header and background set already. Use a JPanel to contain components of the screen and add it to the container object of the  `Screen` class using `container.add(uiContainer, BorderLayout.Center);`.

**Log In & Sign Up Screens**

![SignUp](https://github.com/dbucknor/ap-grizzly-entertainment/assets/103082549/46501594-2b15-4f7c-b6b6-ae1d0651c336)
![LogIn](https://github.com/dbucknor/ap-grizzly-entertainment/assets/103082549/1c7865a8-9c48-419e-ae50-cec45ab21e2b)

**Comment by dorianbucknor** [comment]
Sign up is already done. Please Update project to get latest code
